"""Human-readable documentation, generated EXCLUSIVELY from the canonical machine artifacts.

No prose in this repository's governance docs is hand-written any more, because a hand-written
number is a number that rots — and this codebase's signature defect, found in every one of five
audit cycles, is precisely "the doc names a mechanism that does not exist."

The output of this module is therefore a VIEW, never a SOURCE. Editing it is pointless: the next
`python -m tools.arch docs` overwrites it.
"""
from __future__ import annotations

from pathlib import Path

from .common import DERIVED, REPO, load
from .policy import RULES
from . import registries as reg

_BANNER = ("<!-- GENERATED by `python -m tools.arch docs` — DO NOT EDIT.\n"
           "     Every number below is regenerated from the code. Edit the code, or the DECLARED\n"
           "     artifact it derives from, and re-run the command. -->\n")


def _governance_doc() -> str:
    dep = load(DERIVED / "dependencies.json")
    mod = load(DERIVED / "modules.json")
    se = load(DERIVED / "side_effects.json")
    sf = load(DERIVED / "surfaces.json")
    cfg = load(DERIVED / "configuration.json")
    rat = load(DERIVED / "ratchets.json")
    cs = load(DERIVED / "contract_surface.json")
    uns = load(DERIVED / "unsupported.json")
    man = load(DERIVED / "MANIFEST.json")

    t = dep["totals"]
    L: list[str] = [_BANNER, "# FanOps — Architecture & Implementation Governance", ""]
    # The SOURCE FINGERPRINT identifies the tree, NOT the git commit. A commit SHA here would make
    # this doc differ from its own regeneration the instant it was committed — see common.dumps().
    L += [f"**Source fingerprint `{man['fingerprint']}` · generator `{man['generator_version']}`**", "",
          f"Regenerate: `{man['regeneration_command']}`", "",
          "> This document is a **view**. It is generated from the machine-readable artifacts in "
          "`.reports/architecture/derived/` and `.reports/architecture/governance/`. "
          "It contains no hand-written facts.", "", "---", ""]

    # ── the architecture, in numbers ────────────────────────────────────────────────────────
    L += ["## 1. The architecture, measured", "",
          "| | |", "|---|---|",
          f"| Modules | **{t['modules']}** |",
          f"| Compile-time import edges (G1) | **{t['compile_edges_G1']}** |",
          f"| Lazy (in-function) edges | **{t['lazy_edges']}** |",
          f"| Typing-only edges | {t['typing_only_edges']} |",
          f"| Non-trivial compile-time SCCs | **{t['G1_non_trivial_sccs']}** |",
          f"| Layer levels (G1c, the SCC-condensation) | **{t['G1c_levels']}** |",
          f"| Lazy edges strictly UPWARD (layering inversions) | **{t['lazy_edges_strictly_upward']}** |",
          f"| Lazy edges lateral (same level — *not* inversions) | {t['lazy_edges_lateral']} |",
          f"| Largest G2 potential-dependency SCC | {t['G2_largest_scc_size']} modules |",
          f"| Environment variables read | **{cfg['totals']['env_vars_read']}** |",
          f"| Route endpoints (method × path) | **{sf['totals']['route_endpoints']}** "
          f"({sf['totals']['route_endpoints_mutating']} mutating) |",
          f"| CLI verbs | {sf['totals']['cli_verbs_unique']} unique "
          f"({sf['totals']['cli_add_parser_sites']} `add_parser` sites) |", ""]

    L += ["### Metric definitions — because a derived number inherits the soundness of its definition",
          ""]
    for k, v in sorted(dep["metric_definitions"].items()):
        L.append(f"- **`{k}`** — {v}")
    L.append("")
    for k, v in sorted(sf["metric_definitions"].items()):
        L.append(f"- **`{k}`** — {v}")
    L += ["", "---", ""]

    # ── the subsystem partition ─────────────────────────────────────────────────────────────
    total = mod["partition_is_total"]
    L += ["## 2. The subsystem partition", "",
          f"**Totality: {'✅ TOTAL' if total else '🔴 NOT TOTAL'}** — "
          f"{mod['totals']['assigned']}/{mod['totals']['modules']} modules assigned, "
          f"{mod['totals']['unassigned']} unassigned, {mod['totals']['ghosts']} ghosts.", ""]
    if mod["unassigned_modules"]:
        L += ["Modules belonging to **no subsystem** — no owner, no risk profile, no reviewer:", ""]
        L += [f"- `{m}`" for m in mod["unassigned_modules"]]
        L.append("")
    L += ["> The partition is an **analytic overlay** (Cycle 5). Nothing in the code enforces it. "
          "The module set is a **fact**; the grouping is a **model**. Totality is therefore a "
          "checkable property, and rule `ARCH-001` checks it.", "", "---", ""]

    # ── side effects ────────────────────────────────────────────────────────────────────────
    L += ["## 3. Side effects — the blast radius", "", "| Effect | Sites |", "|---|---|"]
    for k, v in sorted(se["totals"].items()):
        L.append(f"| {k.replace('_', ' ')} | **{v}** |")
    L += ["", f"> {se['known_blind_spot']}", "", "---", ""]

    # ── the ratchets ────────────────────────────────────────────────────────────────────────
    d = rat["declared_by_the_ci_tests"]
    meas = rat["measured"]["print_calls_by_module"].get("fanops.cli")
    L += ["## 4. The ratchets — mechanically enforced in CI today", "",
          f"- `cli.py` `print()` count — **declared by the test: {d['print']['cli_print_count']}** · "
          f"**measured: {meas}** (an *exact-equality* budget shared by three slices)",
          f"- Zero-`print()` modules: {len(d['print']['zero_print_modules'])}",
          f"- Silent-broad-`except` baseline: {len(d['swallow'].get('baseline', {}))} files", ""]
    slack = {f: (v, rat["measured"]["silent_broad_except_by_file"].get(f, 0))
             for f, v in d["swallow"].get("baseline", {}).items()
             if rat["measured"]["silent_broad_except_by_file"].get(f, 0) < v}
    if slack:
        L += ["> ⚠️ **The swallow ratchet carries unclaimed slack.** These files declare a higher "
              "baseline than they currently use, so a future change can re-add a silent handler "
              "without CI noticing:", ""]
        L += [f"> - `{f}` — baseline **{a}**, actual **{b}**" for f, (a, b) in sorted(slack.items())]
        L.append("")
    L += ["---", ""]

    # ── the implementation contract ─────────────────────────────────────────────────────────
    if cs.get("available"):
        L += ["## 5. The implementation contract, resolved against the code", "",
              f"- Slices: **{len(cs['slices'])}** · files under ownership: **{len(cs['files'])}**",
              f"- Ordering DAG acyclic: **{'✅ PROVEN' if cs['dag']['acyclic'] else '🔴 CYCLE'}** "
              f"({len(cs['dag']['ordering_edges'])} ordering edges, "
              f"{len(cs['dag']['co_requirements'])} co-requirements)", ""]
        L += ["> A **co-requirement is not an ordering edge**. Modelling it as one would manufacture "
              "a DAG cycle that does not exist — the `C5-SC-2` error, applied to the implementation "
              "graph.", ""]
        if cs["unresolved_boundaries"]:
            L += ["", f"🔴 **{len(cs['unresolved_boundaries'])} slice boundary/-ies are PROSE, not "
                      f"machine-checkable predicates.** They cannot be enforced by CI as written:", ""]
            for b in cs["unresolved_boundaries"]:
                L.append(f"- `{b['slice']}` · `{b['file']}` — {b['entry']!r}")
            L.append("")
        L += ["---", ""]

    # ── the policy set ──────────────────────────────────────────────────────────────────────
    L += ["## 6. The executable policy set", "",
          "Every rule is a predicate a machine evaluates. `python -m tools.arch check`.", "",
          "| Rule | Severity | Title | Enforcement |", "|---|---|---|---|"]
    for r in sorted(RULES.values(), key=lambda r: r.id):
        L.append(f"| `{r.id}` | {r.severity} | {r.title} | {r.enforcement} |")
    L.append("")
    for r in sorted(RULES.values(), key=lambda r: r.id):
        L += [f"#### `{r.id}` — {r.title}", "",
              f"**Rationale.** {r.rationale}", "",
              f"- **Scope:** `{r.scope}`", f"- **Severity:** {r.severity}",
              f"- **Enforcement:** {r.enforcement}", f"- **Remediation:** {r.remediation}",
              f"- **Exception process:** {r.exception_process}", ""]
    L += ["---", ""]

    # ── registries ──────────────────────────────────────────────────────────────────────────
    open_, ceiling = reg.unknown_growth()
    excs, exps = reg.exceptions(), reg.expired()
    L += ["## 7. Governed exceptions and unknowns", "",
          f"- Exceptions on record: **{len(excs)}** ({len(exps)} expired — an expired exception "
          f"suppresses nothing)",
          f"- Open unknowns: **{open_}** / approved ceiling **{ceiling}**", ""]
    if excs:
        L += ["| ID | Rule | Owner | Expiry | Justification |", "|---|---|---|---|---|"]
        for e in excs:
            L.append(f"| `{e['id']}` | `{e['rule']}` | {e.get('owner')} | {e.get('expiry')} | "
                     f"{e.get('justification','')[:80]} |")
        L.append("")
    unk = reg.unknowns()
    if unk:
        L += ["| ID | Subsystem | Risk | Question |", "|---|---|---|---|"]
        for u in unk:
            L.append(f"| `{u['id']}` | {u.get('subsystem')} | {u.get('risk')} | "
                     f"{u.get('question','')[:90]} |")
        L.append("")
    L += ["---", ""]

    # ── unsupported ─────────────────────────────────────────────────────────────────────────
    L += ["## 8. What the extractor cannot resolve", "",
          f"**{uns['totals']['unsupported_constructs']}** construct(s). Recorded, never dropped — "
          "an omitted construct is indistinguishable from an absent one.", ""]
    if uns["constructs"]:
        L += ["| Module | Line | Kind | Why |", "|---|---|---|---|"]
        for c in uns["constructs"]:
            L.append(f"| `{c['module']}` | {c.get('line','—')} | `{c['kind']}` | {c['why']} |")
        L.append("")
    return "\n".join(L) + "\n"


def expected(repo: Path | None = None) -> dict[Path, str]:
    """The generated docs and their EXACT expected bytes — computed, never written.

    Split out from `render_all` so the FAST GATE can byte-compare a generated doc without
    writing it. `docs/ARCHITECTURE_GOVERNANCE.md` is as generated as anything under `derived/`,
    but it does not live there, so the derived byte-compare never saw it: a hand-edit to the
    governance doc could be merged green and only surface a week later in the scheduled job.
    A generated file that can silently drift is the exact defect this cycle exists to kill.

    `repo=None`, NOT `repo=REPO`. A default argument is evaluated ONCE, at import — so
    `repo: Path = REPO` freezes the module-level REPO forever, and the negative-control fixture,
    which isolates the checkers by reassigning `render.REPO` to a temp tree, could never move it.
    NC-23 duly compared the REAL repository's doc against a FIXTURE-derived expectation, reported
    DETECTED off that unrelated mismatch, and was proving nothing. Resolve the global at CALL time.
    """
    repo = repo or REPO
    return {repo / "docs" / "ARCHITECTURE_GOVERNANCE.md": _governance_doc()}


def render_all() -> list[tuple[str, bool]]:
    out: list[tuple[str, bool]] = []
    for p, text in expected().items():
        out.append((p.relative_to(REPO).as_posix(), _write_text(p, text)))
    return out


def _write_text(path: Path, text: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True
