# src/fanops/lever_docs.py
"""Generated operator docs for persona levers + selection thresholds (MOL-162/MOL-163). Pure reads of the
live registry/effect maps — the committed markdown is pinned by tests so behavior and docs cannot drift."""
from __future__ import annotations
import inspect
from pathlib import Path
from fanops.config import Config
from fanops import persona_levers as pl
from fanops import bands, moments, prompts
from fanops.personas import baked_personas

_REPO_ROOT = Path(__file__).resolve().parents[2]


def _def_line(obj, fallback: str) -> str:
    """`module.py:line` for a function or module attribute (threshold edit pointer)."""
    try:
        if inspect.isfunction(obj) or inspect.ismethod(obj):
            return f"{obj.__module__.replace('.', '/')}.py:{inspect.getsourcelines(obj)[1]}"
        mod = inspect.getmodule(obj)
        if mod and hasattr(obj, "__name__"):
            _, line = inspect.getsourcelines(mod)
            for i, row in enumerate(inspect.getsourcelines(mod)[0], start=line):
                if f"{obj.__name__}" in row and "=" in row:
                    return f"{mod.__name__.replace('.', '/')}.py:{i}"
    except (OSError, TypeError):
        pass
    return fallback


def _mod_const_line(mod, name: str) -> str:
    try:
        _, line = inspect.getsourcelines(mod)
        for i, row in enumerate(inspect.getsourcelines(mod)[0], start=line):
            if row.strip().startswith(f"{name} "):
                return f"{mod.__name__.replace('.', '/')}.py:{i}"
    except OSError:
        pass
    return f"{mod.__name__.replace('.', '/')}.py"


def _content_focus_row(opt: dict) -> str:
    prof = opt.get("profile") or "talk"
    fr = opt.get("framing") or "center"
    tier = opt.get("intensity") or "medium"
    b = bands.band_for(prof)
    clause = opt.get("clause", "")
    det = (f"intensity={tier} → filter_peaks_by_intensity "
           f"({'top' if tier == 'high' else 'bottom' if tier == 'low' else 'unchanged'} tercile); "
           f"derived band={prof} ({b.lo:g}-{b.hi:g}s), framing={fr}")
    cut = f"{prof} clips ({b.lo:g}-{b.hi:g}s), {fr} crop"
    phase = "moments gate (pick) → steers frame-seeing hook author"
    return f"| `{opt['value']}` | {clause!r} | {det} | {cut} | {phase} |"


def _selection_scope_row(opt: dict) -> str:
    clause = opt.get("clause") or "no change — open selection"
    det = "selection constraint only (no band/framing/peak filter)"
    cut = "inherits content_focus-derived cut (or global)"
    phase = "moments gate (casting prompt)"
    return f"| `{opt['value']}` | {clause!r} | {det} | {cut} | {phase} |"


def _hook_angle_row(opt: dict) -> str:
    clause = opt.get("clause", "")
    return (f"| `{opt['value']}` | {clause!r} | hook strategy only (no peak/band geometry) | "
            f"n/a (hook text) | hook gate (moment_hooks) |")


def _clip_profile_row(opt: dict) -> str:
    b = bands.band_for(opt["value"])
    return (f"| `{opt['value']}` | n/a (global band name) | band_for → {b.lo:g}-{b.hi:g}s render window | "
            f"{b.lo:g}-{b.hi:g}s cuts | cut/render (Go-Live default; per-persona derived from content_focus) |")


def archetype_crosswalk_rows() -> list[dict]:
    """One row per shipped baked archetype persona — the crosswalk the operator reads."""
    rows: list[dict] = []
    for p in baked_personas():
        rows.append({"id": p.id, "name": p.name or p.id,
                       "content_focus": list(p.content_focus or []),
                       "hook_angle": (p.hook_angle or "").strip(),
                       "selection_scope": (p.selection_scope or "open").strip(),
                       "intensity": pl.derive_intensity_from_focus(p.content_focus) or "medium",
                       "corpus": list(p.hashtag_corpus or [])})
    return rows


def _archetype_crosswalk_section() -> str:
    lines = ["## ARCHETYPE CROSSWALK", "",
             "Shipped baked personas (`src/fanops/data/baked_personas.json`) — what each does at PICK + HOOK + corpus.",
             "",
             "| id | content_focus (select) | hook_angle | selection_scope | intensity (peak filter) | corpus |",
             "|----|------------------------|------------|-----------------|-------------------------|--------|"]
    for r in archetype_crosswalk_rows():
        corp = ", ".join(r["corpus"][:4]) if r["corpus"] else "—"
        foc = ", ".join(r["content_focus"]) if r["content_focus"] else "—"
        lines.append(f"| `{r['id']}` | {foc} | `{r['hook_angle']}` | `{r['selection_scope']}` | "
                     f"{r['intensity']} | {corp} |")
    return "\n".join(lines)


def render_levers(cfg: Config) -> str:  # cfg reserved for future persona-aware rows; pure today
    hdr = ("# Persona levers — operator rule-of-thumb\n\n"
           "> generated by `fanops lever docs`; do not edit.\n")
    how = ("\n## How to change an option's EFFECT\n\n"
           "| lever / effect | edit |\n"
           "|----------------|------|\n"
           "| content_focus options, clauses, band/framing/intensity | "
           "`src/fanops/persona_levers.py` → `_CONTENT_FOCUS_OPTIONS` / `LEVER_REGISTRY` |\n"
           "| selection_scope clauses | `src/fanops/persona_levers.py` → `_SELECTION_SCOPE_OPTIONS` |\n"
           "| hook_angle clauses | `src/fanops/persona_levers.py` → `_HOOK_ANGLE_OPTIONS` |\n"
           "| clip band seconds | `src/fanops/bands.py` → `_PROFILES` / `TALK`/`SHORT`/… |\n"
           "| peak intensity filter (P4b) | `src/fanops/signals.py` → `filter_peaks_by_intensity` |\n"
           "| derived cut from content_focus | `src/fanops/persona_directives.py` → `derive_cut_spec` |\n"
           "\nThen run `fanops lever docs` to regenerate this file.\n")
    table_hdr = ("\n| value | what it tells the LLM | deterministic operation | cut consequence | phase/gate |\n"
                 "|-------|----------------------|-------------------------|-----------------|------------|")
    parts = [hdr, how]
    for lv in pl.LEVER_REGISTRY:
        key = lv["key"]
        if key == "hashtag_corpus":
            parts.append(f"\n## {key} (stage: {lv['stage']})\n\n"
                         f"**Does:** {lv['does']}\n\n"
                         "Curated tags lead caption hashtags (`hashtags.vet_hashtags`); no enumerated options.\n")
            continue
        parts.append(f"\n## {key} (stage: {lv['stage']})\n\n**Does:** {lv['does']}\n{table_hdr}")
        for opt in lv["options"]:
            if key == "content_focus":
                parts.append(_content_focus_row(opt))
            elif key == "selection_scope":
                parts.append(_selection_scope_row(opt))
            elif key == "hook_angle":
                parts.append(_hook_angle_row(opt))
            elif key == "clip_profile":
                parts.append(_clip_profile_row(opt))
    parts.append("\n" + _archetype_crosswalk_section() + "\n")
    return "\n".join(parts)


def render_thresholds(cfg: Config) -> str:
    hdr = ("# Lever thresholds — selection-layer mechanics\n\n"
           "> generated; ENGINEER-owned mechanics — to change one, edit the named line + regenerate. "
           "Listed for operator review + approval.\n")
    table = ("\n| NAME | current value | what it controls | raising | lowering | edit |\n"
             "|------|---------------|------------------|---------|----------|------|")
    rows: list[str] = []
    for name in ("short", "medium", "long", "talk", "song"):
        b = bands.band_for(name)
        rows.append(f"| `bands.{name}` | {b.lo:g}-{b.hi:g}s | render floor/ceiling + moment-pick window for `{name}` profile | "
                    f"wider `{name}` clips everywhere this band applies | tighter `{name}` clips | "
                    f"`{_mod_const_line(bands, name.upper())}` |")
    rows.append(f"| `_MAX_OVERLAP_FRAC` | {moments._MAX_OVERLAP_FRAC} | two picks overlapping more than this fraction "
                f"of the shorter span are deduped | fewer near-duplicate picks survive | more overlap allowed | "
                f"`{_mod_const_line(moments, '_MAX_OVERLAP_FRAC')}` |")
    rows.append(f"| `_MAX_TARGET_PICKS` | {prompts._MAX_TARGET_PICKS} | per-persona pick ceiling in the moment prompt | "
                f"model may aim for more picks on long sources | fewer picks requested | "
                f"`{_mod_const_line(prompts, '_MAX_TARGET_PICKS')}` |")
    rows.append(f"| `_target_pick_count` | `round(duration / band.span)` capped 1..{prompts._MAX_TARGET_PICKS} | "
                f"how many clips to aim for by source length | more picks on long sources | fewer picks | "
                f"`{_def_line(prompts._target_pick_count, 'src/fanops/prompts.py')}` |")
    rows.append("| `filter_peaks_by_intensity` terciles | `lo_thr = scores[n//3]`, `hi_thr = scores[(2*n)//3]` | "
                "what score counts as high/low energy for P4b peak filtering | stricter slice (fewer peaks kept) | "
                "looser slice | `src/fanops/signals.py` → `filter_peaks_by_intensity` |")
    rows.append(f"| `_MIN_MOMENT_S` | {moments._MIN_MOMENT_S}s | minimum pick duration (noise floor) | "
                f"reject shorter spans | allow shorter picks | `{_mod_const_line(moments, '_MIN_MOMENT_S')}` |")
    rows.append(f"| `_EOF_TOLERANCE_S` | {moments._EOF_TOLERANCE_S}s | pick may extend past probed EOF by this much | "
                f"more EOF overrun tolerated | stricter EOF bound | `{_mod_const_line(moments, '_EOF_TOLERANCE_S')}` |")
    return hdr + table + "\n" + "\n".join(rows) + "\n"


def write_docs(cfg: Config, root: Path | None = None) -> tuple[Path, Path]:
    """Regenerate docs/LEVERS.md + docs/LEVER-THRESHOLDS.md; returns the paths written."""
    base = root or _REPO_ROOT
    docs = base / "docs"
    docs.mkdir(parents=True, exist_ok=True)
    levers_p = docs / "LEVERS.md"
    thresh_p = docs / "LEVER-THRESHOLDS.md"
    levers_p.write_text(render_levers(cfg))
    thresh_p.write_text(render_thresholds(cfg))
    return levers_p, thresh_p


def cmd_lever_docs(cfg: Config) -> int:
    from fanops.log import get_logger
    lp, tp = write_docs(cfg)
    get_logger(cfg)("lever_docs", "-", "wrote", levers=str(lp), thresholds=str(tp))
    return 0
