#!/usr/bin/env bash
set -euo pipefail
# lock-deps.sh — regenerate the hashed CI dependency locks (MOL-195 / CI-15).
#
# These are the REPRODUCIBLE + HASH-VERIFIED inputs CI installs from, so a run resolves the exact same
# versions every time (no silent drift on an upstream release) and pip verifies every artifact's hash
# (supply-chain integrity — pairs with the pip-audit step, MOL-194). This is NOT a raw `pip freeze`: it is
# `pip-compile --generate-hashes`, regenerated by tooling, never hand-edited.
#
#   requirements/ci-unit.txt  — the fast PR gate ([dev,studio,framing]; no torch). [framing] (opencv-python-headless)
#                               is in the UNIT lane because smart_framing defaults ON and the render path
#                               HARD-REQUIRES cv2 (framing.require_cv2 raises when absent) — the ~83 render
#                               tests would otherwise refuse. Detection still fails open to centered (no ffmpeg).
#   requirements/ci-e2e.txt   — the real-tooling job ([dev,studio,transcribe,compose,framing])
#   ([asr] is nightly-only (MOL-197), intentionally NOT locked here.)
#
# Regenerate whenever pyproject.toml dependencies change (the `lockfile drift` CI guard enforces this).
# Run on linux/py3.12 to match CI (locks are CI-authoritative; local macOS wheels differ). Idempotent.
ROOT="$(git rev-parse --show-toplevel)"; cd "$ROOT"
python -m pip install --quiet --upgrade pip-tools
mkdir -p requirements
_compile() { python -m piptools compile --quiet --generate-hashes --allow-unsafe --strip-extras "$@" pyproject.toml; }
_compile --extra dev --extra studio --extra framing                              --output-file requirements/ci-unit.txt
_compile --extra dev --extra studio --extra transcribe --extra compose --extra framing --output-file requirements/ci-e2e.txt
echo "[lock-deps] regenerated: ci-unit.txt ($(grep -c '==' requirements/ci-unit.txt) pkgs), ci-e2e.txt ($(grep -c '==' requirements/ci-e2e.txt) pkgs)"
